export interface RouteInfo {
  path: string;
  title: string;
  icon: string;
  class: string;
  role: string[];
  submenu: RouteInfo[];
}

export const ROUTES: RouteInfo[] = [
  {
    path: '/dashboard',
    title: 'Home',
    icon: 'home',
    class: '',
    role: ['Admin', 'Manager', 'Receptionist'],
    submenu: [],
  },
  {
    path: '/hotel-portfolio',
    title: 'Property Portfolio',
    icon: 'dashboard',
    class: '',
    role: ['Admin', 'Manager'],
    submenu: [],
  },
  {
    path: '',
    title: 'Booking Management',
    icon: 'business_center',
    class: 'menu-toggle',
    role: ['Admin', 'Manager', 'Receptionist'],
    submenu: [
      {
        path: '/booking/all-booking',
        title: 'Reservation List',
        icon: '',
        class: '',
        role: ['Admin', 'Manager', 'Receptionist'],
        submenu: [],
      },
      {
        path: '/booking/add-booking',
        title: 'New Booking',
        icon: '',
        class: '',
        role: ['Admin', 'Manager', 'Receptionist'],
        submenu: [],
      },
      {
        path: '/booking/group-booking',
        title: 'Group Booking',
        icon: '',
        class: '',
        role: ['Admin', 'Manager', 'Receptionist'],
        submenu: [],
      },
      {
        path: '/booking/booking-calendar',
        title: 'Booking Calendar',
        icon: '',
        class: '',
        role: ['Admin', 'Manager', 'Receptionist'],
        submenu: [],
      },
      {
        path: '/booking/cancellation-modification',
        title: 'Cancellation & Modification',
        icon: '',
        class: '',
        role: ['Admin', 'Manager', 'Receptionist'],
        submenu: [],
      },
      {
        path: '/booking/check-in-out',
        title: 'Check-in / Check-out',
        icon: '',
        class: '',
        role: ['Admin', 'Manager', 'Receptionist'],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Room Management',
    icon: 'people_alt',
    class: 'menu-toggle',
    role: ['Admin', 'Manager'],
    submenu: [
      {
        path: '/rooms/room-availability',
        title: 'Room Availability Dashboard',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/rooms/room-types',
        title: 'Room Types & Pricing',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/rooms/room-status',
        title: 'Room Status Monitoring',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/rooms/floor-mapping',
        title: 'Floor Mapping',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/rooms/all-rooms',
        title: 'All Rooms',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/rooms/add-room',
        title: 'Add Room',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/rooms/amenities',
        title: 'Amenities',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Inventory Management',
    icon: 'store',
    class: 'menu-toggle',
    role: ['Admin', 'Manager'],
    submenu: [
      {
        path: '/inventory/stock-management',
        title: 'Stock Management',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/inventory/supplier-management',
        title: 'Supplier Management',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/inventory/purchase-orders',
        title: 'Purchase Orders',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/inventory/consumption-tracking',
        title: 'Consumption Tracking',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/inventory/low-stock-alerts',
        title: 'Low Stock Alerts',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/inventory/store-warehouse',
        title: 'Store & Warehouse',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Front Office Management',
    icon: 'desktop_mac',
    class: 'menu-toggle',
    role: ['Admin', 'Manager'],
    submenu: [
      {
        path: '/front-office/guest-registration',
        title: 'Guest Registration',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/front-office/walk-in-booking',
        title: 'Walk-in Booking',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/front-office/room-allocation',
        title: 'Room Allocation',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/front-office/key-management',
        title: 'Key Management',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/front-office/guest-history',
        title: 'Guest History',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Housekeeping Management',
    icon: 'cleaning_services',
    class: 'menu-toggle',
    role: ['Admin', 'Manager'],
    submenu: [
      {
        path: '/housekeeping/cleaning-schedule',
        title: 'Cleaning Schedule',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/housekeeping/room-cleaning-status',
        title: 'Room Cleaning Status',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/housekeeping/staff-assignment',
        title: 'Staff Assignment',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/housekeeping/laundry-management',
        title: 'Laundry Management',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/housekeeping/maintenance-requests',
        title: 'Maintenance Requests',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Billing & Payments',
    icon: 'receipt',
    class: 'menu-toggle',
    role: ['Admin', 'Manager', 'Receptionist'],
    submenu: [
      {
        path: '/billing/invoice-management',
        title: 'Invoice Management',
        icon: '',
        class: '',
        role: ['Admin', 'Manager', 'Receptionist'],
        submenu: [],
      },
      {
        path: '/billing/payment-collection',
        title: 'Payment Collection',
        icon: '',
        class: '',
        role: ['Admin', 'Manager', 'Receptionist'],
        submenu: [],
      },
      {
        path: '/billing/refund-management',
        title: 'Refund Management',
        icon: '',
        class: '',
        role: ['Admin', 'Manager', 'Receptionist'],
        submenu: [],
      },
      {
        path: '/billing/folio-management',
        title: 'Folio Management',
        icon: '',
        class: '',
        role: ['Admin', 'Manager', 'Receptionist'],
        submenu: [],
      },
      {
        path: '/billing/tax-calculation',
        title: 'Tax Calculation',
        icon: '',
        class: '',
        role: ['Admin', 'Manager', 'Receptionist'],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Guest Management (CRM)',
    icon: 'face',
    class: 'menu-toggle',
    role: ['Admin', 'Manager'],
    submenu: [
      {
        path: '/guest-management/guest-profiles',
        title: 'Guest Profiles',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/guest-management/guest-preferences',
        title: 'Guest Preferences',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/guest-management/loyalty-programs',
        title: 'Loyalty Programs',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/guest-management/feedback-reviews',
        title: 'Feedback & Reviews',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Restaurant',
    icon: 'restaurant',
    class: 'menu-toggle',
    role: ['Admin', 'Manager'],
    submenu: [
      {
        path: '/restaurant/dashboard',
        title: 'Dashboard',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/restaurant/new-order',
        title: 'New Order',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/restaurant/orders',
        title: 'Orders',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/restaurant/tables',
        title: 'Tables',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/restaurant/menu',
        title: 'Menu',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/restaurant/kitchen',
        title: 'Kitchen (KOT)',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
      {
        path: '/restaurant/bills',
        title: 'Bills',
        icon: '',
        class: '',
        role: ['Admin', 'Manager'],
        submenu: [],
      },
    ],
  },
  {
    path: '/daily-diary',
    title: 'Daily Diary',
    icon: 'book',
    class: '',
    role: ['Admin', 'Manager', 'Receptionist'],
    submenu: [],
  },
];
